// GENERATED FROM docs/DESIGN.md — DO NOT EDIT. Run: python scripts/gen_tokens.py
module.exports = {
  colors: {
      'surface': '#f8f9ff',
      'surface-dim': '#cbdbf5',
      'surface-bright': '#f8f9ff',
      'surface-container-lowest': '#ffffff',
      'surface-container-low': '#eff4ff',
      'surface-container': '#e5eeff',
      'surface-container-high': '#dce9ff',
      'surface-container-highest': '#d3e4fe',
      'on-surface': '#0b1c30',
      'on-surface-variant': '#464555',
      'inverse-surface': '#213145',
      'inverse-on-surface': '#eaf1ff',
      'outline': '#777587',
      'outline-variant': '#c7c4d8',
      'surface-tint': '#4d44e3',
      'primary': '#3525cd',
      'on-primary': '#ffffff',
      'primary-container': '#4f46e5',
      'on-primary-container': '#dad7ff',
      'inverse-primary': '#c3c0ff',
      'secondary': '#0058be',
      'on-secondary': '#ffffff',
      'secondary-container': '#2170e4',
      'on-secondary-container': '#fefcff',
      'tertiary': '#571ac0',
      'on-tertiary': '#ffffff',
      'tertiary-container': '#6f3dd9',
      'on-tertiary-container': '#e3d5ff',
      'error': '#ba1a1a',
      'on-error': '#ffffff',
      'error-container': '#ffdad6',
      'on-error-container': '#93000a',
      'success': '#026e4f',
      'on-success': '#ffffff',
      'success-container': '#c3f0da',
      'on-success-container': '#00522f',
      'warning': '#8a5300',
      'on-warning': '#ffffff',
      'warning-container': '#ffddb0',
      'on-warning-container': '#2c1700',
      'neutral': '#5b5b6b',
      'on-neutral': '#ffffff',
      'neutral-container': '#e2e1ec',
      'on-neutral-container': '#1a1a24',
      'info': '#00668b',
      'on-info': '#ffffff',
      'info-container': '#bfe9ff',
      'on-info-container': '#00344a',
      'primary-fixed': '#e2dfff',
      'primary-fixed-dim': '#c3c0ff',
      'on-primary-fixed': '#0f0069',
      'on-primary-fixed-variant': '#3323cc',
      'secondary-fixed': '#d8e2ff',
      'secondary-fixed-dim': '#adc6ff',
      'on-secondary-fixed': '#001a42',
      'on-secondary-fixed-variant': '#004395',
      'tertiary-fixed': '#e9ddff',
      'tertiary-fixed-dim': '#d0bcff',
      'on-tertiary-fixed': '#23005c',
      'on-tertiary-fixed-variant': '#5516be',
      'background': '#f8f9ff',
      'on-background': '#0b1c30',
      'surface-variant': '#d3e4fe',
  },
  borderRadius: {
      'sm': '0.25rem',
      'DEFAULT': '0.5rem',
      'md': '0.75rem',
      'lg': '1rem',
      'xl': '1.5rem',
      'full': '9999px',
  },
  spacing: {
      'base': '8px',
      'container-max': '1440px',
      'gutter': '24px',
      'margin-desktop': '40px',
      'margin-mobile': '20px',
      'stack-lg': '48px',
      'stack-md': '24px',
      'stack-sm': '12px',
  },
  fontFamily: {
    sans: ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
  },
  fontSize: {
      'display-lg': ['48px', { lineHeight: '1.1', fontWeight: '700', letterSpacing: '-0.02em' }],
      'display-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
      'headline-lg': ['30px', { lineHeight: '1.3', fontWeight: '600', letterSpacing: '-0.01em' }],
      'headline-md': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
      'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
      'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
      'label-md': ['14px', { lineHeight: '1.4', fontWeight: '600', letterSpacing: '0.01em' }],
      'label-sm': ['12px', { lineHeight: '1.4', fontWeight: '500' }],
  },
  boxShadow: {
    soft: '0 10px 30px rgba(11, 28, 48, 0.04)',
  },
};
